Version 1.5.16
changelog for i40e-1.5.16
====================================
* Add support for IPv4 encapsulated in IPv6
* Add support for ATR w/ IPv6 extension headers
* Allow up to 12K bytes of data per Tx descriptor instead of 8K
* Add geneve tunnel offload support
* Add VF promiscuous mode support
* Add support for new 10GBaseT PHY's
* Allow RSS Hash set with less than four parameters
* Timestamp bug fixes
* Add support for new kernels
* Fix compile issues on old kernels
* Add new option to irq affinity script
* Disable driver FCoE support
* Add support for flexibility in tuples used for ntuple rules
* Enable RSS for TCP6/UDP6
* Add support for flex bytes in flow director filter
* Add filters to support VSI selection based on L3 and tunnel parameters
* New device support
* Disable link polling

diff --git a/scripts/set_irq_affinity b/scripts/set_irq_affinity
--- a/scripts/set_irq_affinity
+++ b/scripts/set_irq_affinity
@@ -36,8 +36,9 @@
 usage()
 {
 	echo
-	echo "Usage: $0 [-x] {all|local|remote|one|custom} [ethX] <[ethY]>"
+	echo "Usage: $0 [-x|-X] {all|local|remote|one|custom} [ethX] <[ethY]>"
 	echo "	options: -x		Configure XPS as well as smp_affinity"
+	echo "	options: -X		Disable XPS but set smp_affinity"
 	echo "	options: {remote|one} can be followed by a specific node number"
 	echo "	Ex: $0 local eth0"
 	echo "	Ex: $0 remote 1 eth0"
@@ -47,9 +48,35 @@ usage()
 	exit 1
 }
 
+usageX()
+{
+	echo "options -x and -X cannot both be specified, pick one"
+	exit 1
+}
+
 if [ "$1" == "-x" ]; then
 	XPS_ENA=1
 	shift
+fi
+
+if [ "$1" == "-X" ]; then
+	if [ -n "$XPS_ENA" ]; then
+		usageX
+	fi
+	XPS_DIS=2
+	shift
+fi
+
+if [ "$1" == -x ]; then
+	usageX
+fi
+
+if [ -n "$XPS_ENA" ] && [ -n "$XPS_DIS" ]; then
+	usageX
+fi
+
+if [ -z "$XPS_ENA" ]; then
+	XPS_ENA=$XPS_DIS
 fi
 
 num='^[0-9]+$'
@@ -106,10 +133,18 @@ set_affinity()
 
 	printf "%s" $MASK > /proc/irq/$IRQ/smp_affinity
 	printf "%s %d %s -> /proc/irq/$IRQ/smp_affinity\n" $IFACE $core $MASK
-	if ! [ -z "$XPS_ENA" ]; then
+	case "$XPS_ENA" in
+	1)
 		printf "%s %d %s -> /sys/class/net/%s/queues/tx-%d/xps_cpus\n" $IFACE $core $MASK $IFACE $((n-1))
 		printf "%s" $MASK > /sys/class/net/$IFACE/queues/tx-$((n-1))/xps_cpus
-	fi
+	;;
+	2)
+		MASK=0
+		printf "%s %d %s -> /sys/class/net/%s/queues/tx-%d/xps_cpus\n" $IFACE $core $MASK $IFACE $((n-1))
+		printf "%s" $MASK > /sys/class/net/$IFACE/queues/tx-$((n-1))/xps_cpus
+	;;
+	*)
+	esac
 }
 
 # Allow usage of , or -
